# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: python-flask-app
  title: Python Flask App template
  description: A template for creating Python Flask applications
spec:
  owner: IDP
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some parameters
      required:
        - component_name
        - environment
        - api_path
      properties:
        component_name:
          title: Component Name / App Name
          type: string
          description: Unique name of the component (microservice/app)
        environment:
          title: Environment
          type: string
          description: Environment of the component
          enum:
            - dev
            - pdn
        api_path:
          title: API subpath to expose the service
          type: string
          description: subpath to expose the service (/api/v1/{subpath})

#    - title: Choose a location
#      required:
#        - repoUrl
#      properties:
#        repoUrl:
#          title: Repository Location
#          type: string
#          ui:field: RepoUrlPicker
#          ui:options:
#            allowedHosts:
#              - github.com

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          component_name: ${{ parameters.component_name }}
          environment: ${{ parameters.environment }}
          api_path: ${{ parameters.api_path }}

#    - id: fetchDocs
#      name: Fetch Docs
#      action: fetch:plain
#      input:
#        targetPath: ./community
#        url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.component_name }}
        repoUrl: github.com?owner=YuneZoft&repo=${{ parameters.component_name }}
#        defaultBranch: 'main'
        protectDefaultBranch: false

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}